version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: markdown_production_django
    depends_on:
      - postgres
      - redis
    command: /start
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: markdown_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups

  redis:
    image: redis:5.0
